### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by bruxelles86** [baileytalks/makers-bnb-broken#1]
As a user
So that I can use Makersbnb
I would like make an account

**Comment by baileytalks** [comment]
We've built a basic html page with a sign up form, with name, email and password (not currently encrypted).

We also tried to 'post' the form params into the sequelize database, but without the relevant routes (using Express) we can't make it work.

I've saved the code we worked on today on my local machine so that we can come back to it when we've done the necessary Express setup.
